apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-service
spec:
  type: NodePort
  ports:
  - port: 18080
    targetPort: 18080
    nodePort: 30080
  selector:
    app: spark-history-server
